language: python
python:
  - "3.7"
# command to install dependencies

  
before_install:
  - sudo apt-get update
  
install:
  - pip install -r requirements.txt
  - pip install -e .
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  # install requirements for testing
  - pip install codecov
  - pip install pytest pytest-cov

script:  
  #- py.test tests/ --setup-only
  #- sh tests/run_tests.sh
  - pytest --cov=./ tests

after_success:
  - codecov